Custom boats compatibility
FrostHexABG/TimingSystem pull request #40
Opened 2024-11-21 02:59 UTC by jewtvet

Custom boats

2024-12-20 17:15 UTC, Makkuusen commented
So merging these changes would partially remove the default behavior of boats in TimingSystem. If you are coding an addon, I would suggest you add optional config to disable the standard behavior instead, but not fully remove it.

2024-12-20 18:15 UTC, JustBru00 commented
> So merging these changes would partially remove the default behavior of boats in TimingSystem. If you are coding an addon, I would suggest you add optional config to disable the standard behavior instead, but not fully remove it.

I agree with this. This PR will need modifications before implementation so that default behavior isn't broken.

2025-01-17 00:10 UTC, JustBru00 requested changes
Please modify the name of the config.yml key from `customboats` to `customboatsaddon`.

This will add clarity for public TimingSystem users.

2025-01-17 00:10 UTC, JustBru00 commented on src/main/java/me/makkuusen/timing/system/TimingSystemConfiguration.java
> +    private final boolean customBoatsEnabled;
Please change to `customBoatsAddOnEnabled`.

2025-01-17 00:10 UTC, JustBru00 commented on src/main/java/me/makkuusen/timing/system/TimingSystemConfiguration.java
> +        customBoatsEnabled = plugin.getConfig().getBoolean("customboats.enabled");
Please change config.yml key to `customboatsaddon.enabled`

2025-01-17 00:10 UTC, JustBru00 commented on src/main/java/me/makkuusen/timing/system/TimingSystemConfiguration.java
> +        guiPrefix3 = plugin.getConfig().getString("customboats.guiprefix3");
Please change config.yml key to `customboatsaddon.guiprefix3`

2025-01-17 00:10 UTC, JustBru00 commented on src/main/java/me/makkuusen/timing/system/TimingSystemConfiguration.java
> +        guiPrefix4 = plugin.getConfig().getString("customboats.guiprefix4");
Please change config.yml key to `customboatsaddon.guiprefix4`

2025-01-17 00:10 UTC, JustBru00 commented on src/main/java/me/makkuusen/timing/system/TimingSystemConfiguration.java
> +        guiPrefix5 = plugin.getConfig().getString("customboats.guiprefix5");
Please change config.yml key to `customboatsaddon.guiprefix5`

2025-01-17 00:10 UTC, JustBru00 commented on src/main/java/me/makkuusen/timing/system/TimingSystemConfiguration.java
> +        guiPrefix6 = plugin.getConfig().getString("customboats.guiprefix6");
Please change config.yml key to `customboatsaddon.guiprefix6`

2025-01-17 00:10 UTC, JustBru00 commented on src/main/java/me/makkuusen/timing/system/commands/CommandSettings.java
> +        if (TimingSystem.configuration.isCustomBoatsEnabled()) {
Change to `TimingSystem.configuration.isCustomBoatsAddOnEnabled()`

2025-01-17 00:10 UTC, JustBru00 commented on src/main/java/me/makkuusen/timing/system/gui/SettingsGui.java
> +        if (!TimingSystem.configuration.isCustomBoatsEnabled()) {
Please change to `TimingSystem.configuration.isCustomBoatsAddOnEnabled()`

2025-01-17 00:10 UTC, JustBru00 commented on src/main/java/me/makkuusen/timing/system/theme/Text.java
> +        var text = (TimingSystem.configuration.isCustomBoatsEnabled() ? TimingSystem.configuration.getGuiPrefix3() : "") + TimingSystem.getLanguageManager().getNewValue(key.getKey(), getLocale(sender
Please change to `TimingSystem.configuration.isCustomBoatsAddOnEnabled()`

2025-01-17 00:10 UTC, JustBru00 commented on src/main/resources/config.yml
> +customboats:
Please change config.yml key to `customboatsaddon`

2025-01-17 00:35 UTC, JustBru00 approved these changes

2025-01-17 00:36 UTC, merged